### ISSUE TITLE
Error with this module

### ISSUE THREAD

**Issue by Adel51** [werthdavid/MMM-Bring#18]
Hi,
When I add your module, I have the error : 
[2020-11-07 20:19:03.086] [ERROR]  (node:10421) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
[2020-11-07 20:19:03.090] [ERROR]  (node:10421) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
[2020-11-07 20:19:03.095] [ERROR]  (node:10421) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by t                        hrowing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2020-11-07 20:19:03.097] [ERROR]  (node:10421) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by t                        hrowing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2020-11-07 20:19:03.099] [ERROR]  (node:10421) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promis                        e rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-11-07 20:19:03.101] [ERROR]  (node:10421) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promis                        e rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-11-07 20:19:58.873] [ERROR]  (node:10421) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
[2020-11-07 20:19:58.883] [ERROR]  (node:10421) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
[2020-11-07 20:19:58.886] [ERROR]  (node:10421) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by t                        hrowing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[2020-11-07 20:19:58.888] [ERROR]  (node:10421) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by t                        hrowing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[2020-11-07 20:20:58.225] [ERROR]  (node:10421) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
[2020-11-07 20:20:58.231] [ERROR]  (node:10421) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/pi/MagicMirror/modules/MMM-Bring/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
[2020-11-07 20:20:58.233] [ERROR]  (node:10421) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by t                        hrowing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
[2020-11-07 20:20:58.235] [ERROR]  (node:10421) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by t                        hrowing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
^C[2020-11-07 20:21:09.422] [LOG]    Shutting down server...

HELP!

**Comment by werthdavid** [comment]
Hey, have you maybe specified a list that doesn't exist? How does your config look like?

**Comment by Adel51** [comment]
Hi,
Thanks to answer. 
I decided to test it today again. Now, I have no error but i see nothing on my MM from your module.
here is my config.js :  
'''javascript
		{
			module: "MMM-Bring",
			position: "bottom_bar",
			config: {
			   email: "atouajar@gmail.com",
			   password: "Abdel51",
			   updateInterval: 15, // in Minutes
			   listName: "Maison", // optional
			   showListName: true,
			   activeItemColor: "#EE524F",
			   latestItemColor: "#4FABA2",
			   showLatestItems: false,
			   maxItems: 0,
			   maxLatestItems: 0,
			   locale: "fr-FR", //"de-DE",
			   useKeyboard: false
			}
		},

**Comment by werthdavid** [comment]
Nothing special there... Ill take a look on my side

**Comment by werthdavid** [comment]
I'm getting the error on first login as well but the list still displays... can you confirm that?

**Comment by Adel51** [comment]
hi,
no error and no display !

**Comment by Adel51** [comment]
Hi, I tried it this morning and now Everything is ok.
It's my fault i think because the module was installed in the MM directory and not the modules one. I don't know how it's possible but i did it ;-)
sorry and thx for this great module.
